# Generated by Django 3.2 on 2023-09-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите имя пользователя', max_length=150, unique=True, verbose_name='Никнейм пользователя'),
        ),
    ]
